ForNeVeR/O21

.github/workflows/main.yml
O21.sln

CI: enable GitHub Actions

---

README.md

Docs: add game and name history

---

CONTRIBUTING.md
O21.sln
README.md

Docs: add contributor guide

---

.gitignore
O21.Game/O21.Game.fsproj
O21.Game/O21Game.fs
O21.Game/Program.fs
O21.sln
README.md

Add MonoGame project template

---

CONTRIBUTING.md
O21.sln
README.md
docs/resources.md

Results of research performed in #5 are now extracted into the doc.

Docs: document the available resources

---

CONTRIBUTING.md
README.md
docs/resources.md

Docs: update the game links

---

docs/resources.md

Docs: document the game sounds

---

docs/resources.md

Docs: document the *.DAT files

---

O21.Game/O21.Game.fsproj
O21.Game/O21Game.fs
O21.Game/U95/Level.fs
O21.Game/U95/Parser.fs

Implement .DAT file parser
Closes #24.

Part of #24

---

O21.Game/O21.Game.fsproj
O21.Game/O21Game.fs
O21.Game/U95/Background.fs
O21.Game/U95/Level.fs
O21.Game/U95/Parser.fs
O21.Game/U95/Sprites.fs
O21.Resources/Dib.fs
docs/resources.md

Closes #17
Implement background rendering. Added logic for reading bmp files with new color depth into Dib.fs

(#17) Backgrounds: Implement background rendering

---

O21.Game/Game.fs
O21.Game/Input.fs
O21.Game/O21.Game.fsproj
O21.Game/O21Game.fs
O21.Game/Program.fs

(#39) Implement basic game architecture

---

O21.Game/O21.Game.fsproj
O21.Game/O21Game.fs
O21.Game/U95/Fish.fs
O21.Game/U95/Level.fs
O21.Game/U95/Sprites.fs
O21.Resources/Dib.fs

Sprites: Extract sprites from PIC.DLL

---

.github/workflows/main.yml
.gitmodules
O21.Game/O21.Game.fsproj
O21.Game/Program.fs
O21.MRB/MrbFile.cs
O21.MRB/O21.MRB.csproj
O21.MRB/ShgFileHeader.cs
O21.MRB/ShgImageHeader.cs
O21.MRB/ShgMetafileHeader.cs
O21.StreamUtil/StreamEx.cs
O21.WinHelp/Topics/FormatHeader.cs
O21.sln

Yet another part of #19.
- Depends on https://github.com/wieslawsoltes/wmf/pull/1

Help: read WMF files

---

.gitmodules

This way, it'll be easier for contributors to checkout the submodule.

wmf: change to HTTPS

---

O21.Game/HUD.fs
O21.Game/HUDRenderer.fs
O21.Game/O21.Game.fsproj
O21.Game/Scenes/PlayScene.fs
O21.Game/U95/HUDSprites.fs
O21.Game/U95/Sprites.fs

Implemented HUD`s render logic.
Closes #16.

(#16)HUD: Implement HUD

---

O21.Game/Documents/DocumentFragments.fs
O21.Game/O21.Game.fsproj
O21.Game/Program.fs
O21.Game/Resources/Inter.spritefont
O21.Game/Scenes/HelpScene.fs
O21.Game/Scenes/MainMenuScene.fs
O21.Game/U95/Help.fs
O21.Game/U95/Sprites.fs
O21.Game/U95/U95Data.fs
O21.WinHelp/Fonts/FontFile.cs

Render help page

---

O21.Game/Game.fs
O21.Game/GameWorld.fs
O21.Game/O21.Game.fsproj
O21.Game/O21Game.fs
O21.Game/Scenes/PlayScene.fs
O21.Game/U95/GameRules.fs
O21.Game/U95/Parser.fs
O21.Game/U95/Sound.fs
O21.Game/U95/U95Data.fs

Add sound system

---

O21.Game/Scenes/HelpScene.fs
O21.Game/Scenes/MainMenuScene.fs

Add "Back" button

---

.github/workflows/main.yml
.gitmodules
O21.MRB/O21.MRB.csproj
O21.sln

This removes a `wmf` submodule.
Closes #50.

Migrate to Oxage.Wmf 0.6.1

---

O21.Game/Scenes/Button.fs
O21.Game/Scenes/HelpScene.fs
O21.Game/Scenes/MainMenuScene.fs
O21.Game/Scenes/PlayScene.fs

I made the buttons more similar to the version from the original version of the game.

Buttons: add design

---

O21.Game/HUD.fs
O21.Game/HUDRenderer.fs
O21.Game/O21.Game.fsproj
O21.Game/Scenes/Button.fs
O21.Game/Scenes/GameOverWindow.fs
O21.Game/Scenes/MainMenuScene.fs
O21.Game/Scenes/MinimizeButton.fs
O21.Game/Scenes/PlayScene.fs
O21.Game/Scenes/WindowRenderer.fs
O21.Game/U95/Sprites.fs

Add "game over" window

---

CONTRIBUTING.md
docs/resources.md

I have reuploaded it as a ZIP for easier processing.

Docs: update the content file and hash

---

O21.Game/Game.fs
O21.Game/Program.fs
O21.Game/Scenes/MainMenuScene.fs
O21.Game/U95/Background.fs
O21.Game/U95/Sprites.fs

Implement Title Screen

---

O21.Game/Game.fs
O21.Game/GameEngine.fs
O21.Game/O21.Game.fsproj
O21.Game/Scenes/PlayScene.fs
O21.Game/State.fs
O21.Game/U95/GameRules.fs
O21.Tests/GameEngineTests.fs
O21.Tests/O21.Tests.fsproj

Introduce a rudimentary GameEngine, support sprite animations

---

O21.Game/Game.fs
O21.Game/Help/DocumentFragments.fs
O21.Game/Help/HlpFile.fs
O21.Game/Help/MarkdownHelp.fs
O21.Game/Loader.fs
O21.Game/Loading/DisclaimerScene.fs
O21.Game/Loading/DownloadScene.fs
O21.Game/Loading/LoadingLoop.fs
O21.Game/Loading/LoadingScene.fs
O21.Game/Loading/LoadingSceneBase.fs
O21.Game/Loading/PreloadingScene.fs
O21.Game/LocalContent.fs
O21.Game/Music.fs
O21.Game/O21.Game.fsproj
O21.Game/Program.fs
O21.Game/RaylibUtils.fs
O21.Game/TextureUtils.fs
O21.Game/U95/BonusSprites.fs
O21.Game/U95/Fish.fs
O21.Game/U95/HUDSprites.fs
O21.Game/U95/Sprites.fs
O21.Game/U95/U95Data.fs

Use Lifetime for resource management

---

O21.Game/Engine/Entities.fs
O21.Game/Engine/ExternalEffect.fs
O21.Game/Engine/GameEngine.fs
O21.Game/Engine/GameField.fs
O21.Game/Engine/GameRules.fs
O21.Game/Engine/Player.fs
O21.Game/Engine/PlayerCommand.fs
O21.Game/Input.fs
O21.Game/O21.Game.fsproj
O21.Game/Scenes/PlayScene.fs
O21.Game/U95/Sprites.fs
O21.Tests/GameEngineTests.fs

Closes #23.
Closes #121: I've decided to make sprites more "material" and have corners and sizes and whatever else is required. This allows us to not operate on sprite centers anymore.
Closes #128.

Implement shooting on the new game engine

---

O21.Game/Controls.fs
O21.Game/HUD.fs
O21.Game/HUDRenderer.fs
O21.Game/O21.Game.fsproj
O21.Game/Scenes/PlayScene.fs

Closes #77 
https://github.com/ForNeVeR/O21/assets/81583669/5e030732-cdc4-4919-8dfa-a0f9199b550a

Сontrol via hud buttons

---

O21.Game/Game.fs
O21.Game/Input.fs
O21.Game/RaylibEnvironment.fs
O21.Game/Scenes/GameOverScene.fs
O21.Game/Scenes/HelpScene.fs
O21.Game/Scenes/MainMenuScene.fs
O21.Game/Scenes/PlayScene.fs
O21.Game/State.fs

I added cameras to scenes and aligned the game scene to the center of the window.
Closes #134.

Camera and play scene alignment

---

O21.Game/Config.fs
O21.Game/Engine/GameRules.fs
O21.Game/Game.fs
O21.Game/O21.Game.fsproj
O21.Game/Program.fs
O21.Game/Scenes/HelpScene.fs
O21.Game/Scenes/MainMenuScene.fs
O21.Game/Scenes/PlayScene.fs
O21.Game/State.fs

Some changes for scenes resize and align

---

O21.Game/Program.fs

Screen resolution argument

---

O21.Game/Engine/Entities.fs
O21.Game/Engine/GameEngine.fs
O21.Game/Scenes/PlayScene.fs

Closes #129 
I am not sure is it a good way

Add previous direction to Player type

---

O21.Game/Config.fs
O21.Game/Engine/GameRules.fs
O21.Game/Game.fs
O21.Game/Loading/DisclaimerScene.fs
O21.Game/Loading/DownloadScene.fs
O21.Game/Loading/LoadingLoop.fs
O21.Game/Loading/LoadingScene.fs
O21.Game/Loading/LoadingSceneBase.fs
O21.Game/Loading/PreloadingScene.fs
O21.Game/LocalContent.fs
O21.Game/O21.Game.fsproj
O21.Game/Program.fs
O21.Game/RaylibEnvironment.fs
O21.Game/Scenes/Button.fs
O21.Game/Scenes/GameOverScene.fs
O21.Game/Scenes/HelpScene.fs
O21.Game/Scenes/MainMenuScene.fs
O21.Game/State.fs
O21.Game/WindowParameters.fs

Add default screen size

---

O21.Game/Loader.fs
O21.Game/Loading/DisclaimerScene.fs
O21.Game/Loading/LoadingLoop.fs
O21.Game/Loading/LoadingSceneBase.fs
O21.Game/Loading/PreloadingScene.fs

Disclaimer scene: migrate to the new scaling approach

---

.config/dotnet-tools.json
.github/workflows/main.yml
CONTRIBUTING.md

This helps to remove the requirement of .NET Core 3.1.

Build: update Svg.Skia to 1.0.0.2

---

O21.Game/Game.fs
O21.Game/Loading/LoadingLoop.fs
O21.Game/Music.fs
O21.Game/O21.Game.fsproj
O21.Game/QueueSynchronizationContext.fs
O21.Game/State.fs

Async sound font and music loading is implemented

---

O21.Game/Game.fs
O21.Game/Music.fs
O21.Game/Scenes/PlayScene.fs

Closes #137.
Closes #154 (this is a rebased version of same PR).

Make music still play during game window resize

---

O21.Game/Engine/Entities.fs
O21.Game/Engine/GameEngine.fs
O21.Game/Engine/GameField.fs
O21.Game/Engine/GameRules.fs
O21.Game/Engine/ParticlesSource.fs
O21.Game/O21.Game.fsproj
O21.Game/Scenes/PlayScene.fs
O21.Game/U95/Sprites.fs
O21.Tests/GameEngineTests.fs

Issue [#66]
Now, bubbles spawn from the stern of submarine. There are settings: Velocity, Period (ticks per particle), Range of offsets from base point. I have selected a configuratuion, that is approximately similar to the original game.
Test case chek that generator create bubble, when the period expired.
Closes #66.

Player particles drawing implemented

---

O21.Game/Engine/Entities.fs
O21.Game/Engine/GameEngine.fs
O21.Game/Engine/GameField.fs
O21.Game/Engine/GameRules.fs
O21.Game/Engine/Geometry.fs
O21.Game/Game.fs
O21.Game/O21.Game.fsproj
O21.Game/Scenes/PlayScene.fs
O21.Game/U95/Level.fs
O21.Game/U95/U95Data.fs
O21.Tests/GameEngineTests.fs

Bullet with wall collisions

---

O21.Game/Game.fs
O21.Game/Music.fs

So that it's no longer that darn loud!

Music: use common sound volume control

---

O21.Game/Engine/Entities.fs
O21.Game/Engine/GameEngine.fs
O21.Game/Engine/GameRules.fs
O21.Game/Engine/ParticlesSource.fs
O21.Game/O21.Game.fsproj
O21.Game/Scenes/PlayScene.fs
O21.Tests/GameEngineTests.fs

Scope: #26.
Decorative bubbles now disappear if they touch the ceiling.

Bubble collisions

---

O21.Game/Engine/Entities.fs
O21.Game/Engine/GameEngine.fs
O21.Game/Engine/GameField.fs
O21.Game/Engine/GameRules.fs
O21.Tests/GameEngineTests.fs

Closes #178
I played a original game and found that the bullet disappears after a certain time. I tried to choose the time of disappearance as close as possible to the original game.

Bullet disappears after the time has elapsed

---

O21.Game/Engine/Entities.fs
O21.Game/Engine/GameEngine.fs
O21.Game/Engine/GameField.fs
O21.Game/Engine/GameRules.fs
O21.Game/Engine/ParticlesSource.fs
O21.Tests/GameEngineTests.fs

Closes #183
Now, velocity of bullets and bubbles is not static, but is calculated depending on the velocity of the submarine.
Added new tests that check this game mechanic.

Bubbles and bullets: additional velocity

---

O21.Game/Game.fs
O21.Game/Scenes/GameOverScene.fs
O21.Game/Scenes/PlayScene.fs

Bug fixed (Issue #194) and improved code a bit

Minor refactoring and bug fixing

---

O21.sln
README.md
docs/command-line.md

Added new file `command-line.md`, that describes CLI
Closes #156

Docs update

---

O21.Game/AnimationType.fs
O21.Game/Animations/Animation.fs
O21.Game/Animations/AnimationHandler.fs
O21.Game/Animations/PlayerAnimation.fs
O21.Game/Engine/Entities.fs
O21.Game/Engine/ExternalEffect.fs
O21.Game/Engine/GameEngine.fs
O21.Game/Engine/GameRules.fs
O21.Game/Game.fs
O21.Game/O21.Game.fsproj
O21.Game/Scenes/PlayScene.fs
O21.Game/U95/Sprites.fs

I suggest use such animation system model: threre are AnimationHandler (collect all animations and update/draw them), Animation (switch frames), [Entity name]Animation (represent animation control for certain entities).
Now, there is only an animation controller for the player (In future we can unify them into one type for player an fishes).
I also added the following animation features:
* Animation speed control
* Loops count control
* Direction of animation (direct and reverse)
Other changes and improvements in this pr:
* Player freezes when taking damage
* Engine can forward type of animation to play
* The submarine's propeller rotates depending on the direction and speed
* Moved comment #123 to the top of the file PlayerAnimation.fs
Part of #122

Player sprite animation and animation system

---

O21.Game/Engine/Entities.fs
O21.Game/Engine/Environments.fs
O21.Game/Engine/GameEngine.fs
O21.Game/Engine/GameRules.fs
O21.Game/HUD.fs
O21.Game/Scenes/PlayScene.fs
O21.Game/U95/Level.fs
O21.Game/U95/Sprites.fs
O21.Tests/GameEngineTests.fs
O21.Tests/Helpers.fs

Implement bonus system and all abilities.
PR closes:
Part of #26

Bonus system

---

O21.Game/Engine/GameEngine.fs

O21's behavior corresponds to the original game at these.
Closes #26.

Get rid of the remaining TODOs

---

CONTRIBUTING.md
Directory.Build.props
O21.CommandLine.Tests/Tests.fs
O21.CommandLine/Arguments.fs
O21.CommandLine/CommandLineParser.fs
O21.CommandLine/O21.CommandLine.fsproj
O21.CommandLine/O21Environment.fs
O21.Game/Loading/LoadingLoop.fs
O21.Game/LocalContent.fs
O21.Game/Localization/Translations.fs
O21.Game/Paths.fs
O21.Game/Program.fs
O21.Game/U95/Level.fs
README.md

Invoke the start command by default

---

O21.Game/Svg.props

Build: fix portable slash processing

---

O21.sln
O21.sln.license
README.md
docs/original-game-behavior.md

Not all the measurements are as precise as I wish them to be, but let's have them at least in this state anyway.

(#27) Document the original enemy behavior

---

O21.Game/Animations/Animation.fs
O21.Game/Animations/PlayerAnimation.fs
O21.Game/Engine/Entities.fs
O21.Game/Engine/GameEngine.fs
O21.Game/Engine/GameTimer.fs
O21.Game/Engine/ParticlesSource.fs
O21.Game/Engine/PlayerCommand.fs
O21.Game/Engine/TickEngine.fs
O21.Game/Game.fs
O21.Game/HUD.fs
O21.Game/O21.Game.fsproj
O21.Game/Scenes/PlayScene.fs
O21.Game/State.fs
O21.Tests/GameEngineTests.fs
O21.Tests/Helpers.fs
O21.Tests/O21.Tests.fsproj
O21.Tests/TickEngineTests.fs

Tick Engine

---

.github/workflows/main.yml
O21.Game/Animations/Animation.fs
O21.Game/Animations/PlayerAnimation.fs
O21.Game/Engine/Entities.fs
O21.Game/Engine/GameEngine.fs
O21.Tests/AnimationTests.fs
O21.Tests/GameEngineTests.fs
O21.Tests/Helpers.fs
O21.Tests/O21.Tests.fsproj
Scripts/github-actions.fsx

Now the score cannot be less then 0, the player's animation has been fixed, and the animation `Direction` has been added.

Fix score system and animations

---

O21.Game/Engine/Enemies.fs
O21.Game/Engine/Environments.fs
O21.Game/Engine/GameEngine.fs
O21.Game/Engine/GameRules.fs
O21.Tests/EnemyTests.fs

Fish: randomize speed, adjust vertical speed

---

O21.Game/DrawSceneHelper.fs
O21.Game/Game.fs
O21.Game/Loader.fs
O21.Game/Loading/DisclaimerScene.fs
O21.Game/Loading/LoadingLoop.fs
O21.Game/Loading/LoadingSceneBase.fs
O21.Game/Loading/PreloadingScene.fs
O21.Game/Scenes/GameOverScene.fs
O21.Game/Scenes/HelpScene.fs
O21.Game/Scenes/MainMenuScene.fs
O21.Game/Scenes/PlayScene.fs
O21.Game/State.fs

Refactor camera control, fix scaling

---

O21.Game/Animations/AnimationHandler.fs
O21.Game/Engine/Enemies.fs
O21.Game/Engine/Entities.fs
O21.Game/Engine/EntityId.fs
O21.Game/Engine/GameEngine.fs
O21.Game/Engine/ReproducibleRandom.fs
O21.Game/Engine/SequentialIdGenerator.fs
O21.Game/O21.Game.fsproj
O21.Tests/EnemyTests.fs
O21.Tests/Helpers.fs

One of steps to making the game reproducible. Issue #274

Replace GUID with strongly typed IDs.

---

.github/workflows/main.yml
.github/workflows/release.yml
Scripts/github-actions.fsx

CI: auto version for checkout and setup-dotnet
